AllCops:
  TargetRubyVersion: 2.3
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'specs/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*.rb'
    - 'cookbooks/**/*.rb'
    - 'cookbooks.v4/**/*.rb'
    - 'db/**/*.rb'
    - 'lib/geolocal.rb'
    - 'node_modules/**/*.rb'
    - 'vendor/**/*'

Rails:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/RescueException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Max: 5

Metrics/ClassLength:
  Max: 2000

Metrics/CyclomaticComplexity:
  Max: 50

Metrics/LineLength:
  Max: 1000

Metrics/MethodLength:
  Max: 500

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Enabled: false

Performance/Count:
  Enabled: false

Performance/Detect:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/Validation:
  Enabled: false

Security/Eval:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/AlignArray:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/ConstantName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/EmptyLineBetweenDefs:
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MethodMissing:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 10

Style/OneLineConditional:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/SpaceAfterColon:
  Enabled: false

Style/SpaceAfterComma:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/VariableNumber:
  Enabled: false
